### ISSUE TITLE
lb-ng Not generating Models ( Cannot find module 'loopback' ) with STR

### ISSUE THREAD

**Issue by ssegeo** [strongloop/loopback-sdk-angular#139]
I am failing to generate my models, here is the STR
[Sandbox Repository](https://github.com/ssegeo/loopback-sandbox)

```
#first cleared the repository directory
#working in the repository directory

#bootstrap the app - ok
slc loopback

#tested the server - ok
slc run .

#I shut it down an create a dummy model - ok

C:\UwAmp\www\loopback-sandbox>slc loopback:model
? Enter the model name: dummy
? Enter the model name: dummy
? Select the data-source to attach dummy to: db (memory)
? Select model's base class: PersistedModel
? Expose dummy via the REST API? Yes
? Custom plural form (used to build REST URL): dummy
Let's add some dummy properties now.

Enter an empty property name when done.
? Property name: name
   invoke   loopback:property
? Property type: string
? Required? No

Let's add another dummy property.
Enter an empty property name when done.
? Property name: label
   invoke   loopback:property
? Property type: string
? Required? No


# I attempt to generate my angular models - Fail

C:\UwAmp\www\loopback-sandbox>cd client

C:\UwAmp\www\loopback-sandbox\client>md js

C:\UwAmp\www\loopback-sandbox\client>lb-ng ../server/server.js js/models.js
Loading LoopBack app "C:\\UwAmp\\www\\loopback-sandbox\\server\\server.js"

module.js:340
    throw err;
    ^
Error: Cannot find module 'loopback'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at assertLoopBackVersion (C:\Users\devUser\AppData\Roaming\npm\node_modules\strongloop\node_modules\loopback-sdk-angular-cli\bin\lb-ng:59:25)
    at Object.<anonymous> (C:\Users\devUser\AppData\Roaming\npm\node_modules\strongloop\node_modules\loopback-sdk-angular-cli\bin\lb-ng:25:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)

#Environment
C:\UwAmp\www\loopback-sandbox\client>node --version
v0.10.28

C:\UwAmp\www\loopback-sandbox\client>cmd
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\UwAmp\www\loopback-sandbox\client>slc --version
strongloop v3.0.4 (node v0.10.28)
├── strong-arc@1.1.0
├── strong-build@1.0.3
├── strong-deploy@1.1.6
├── strong-pm@3.1.9
├── strong-registry@1.1.4
├── strong-start@1.0.3
├─┬ strong-supervisor@1.4.1
│ └── strong-agent@1.3.2
├── generator-loopback@1.9.0
├── node-inspector@0.7.4
└── nodefly-register@0.3.3
```
@bajtos I hope this gives you a clear picture

**Comment by bajtos** [comment]
Hi @ssegeo, thank you for reporting the issue. We are already discussing the problem in https://github.com/strongloop/loopback-sdk-angular-cli/issues/14, let's move there please.

I am closing this issue as a duplicate.
