### ISSUE TITLE
Error stack trace when rendering ejs

### ISSUE THREAD

**Issue by hikkyu** [strongloop/loopback-sdk-angular#161]
Hello!

I got this stack trace when I execute it: 
```shell
Generating "lbServices" for the API endpoint "/api"
undefined:25
  throw err;
        ^
TypeError: ejs:439
    437| <% } -%>
    438|          *
 >> 439|          * @description
    440|          *
    441| <% if (!action.description) {
    442| action.description =  '<em>\n' +

undefined is not a function
    at eval (eval at <anonymous> (/Users/berseron/npm/lib/node_modules/strongloop/node_modules/loopback-sdk-angular-cli/node_modules/loopback-sdk-angular/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:105:25)
    at Array.forEach (native)
    at ngdocForMethod (eval at <anonymous> (/Users/berseron/npm/lib/node_modules/strongloop/node_modules/loopback-sdk-angular-cli/node_modules/loopback-sdk-angular/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:104:10)
    at eval (eval at <anonymous> (/Users/berseron/npm/lib/node_modules/strongloop/node_modules/loopback-sdk-angular-cli/node_modules/loopback-sdk-angular/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:41:92)
    at Array.forEach (native)
    at eval (eval at <anonymous> (/Users/berseron/npm/lib/node_modules/strongloop/node_modules/loopback-sdk-angular-cli/node_modules/loopback-sdk-angular/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:40:87)
    at eval (eval at <anonymous> (/Users/berseron/npm/lib/node_modules/strongloop/node_modules/loopback-sdk-angular-cli/node_modules/loopback-sdk-angular/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:111:50)
    at /Users/berseron/npm/lib/node_modules/strongloop/node_modules/loopback-sdk-angular-cli/node_modules/loopback-sdk-angular/node_modules/ejs/lib/ejs.js:255:15
    at Object.exports.render (/Users/berseron/npm/lib/node_modules/strongloop/node_modules/loopback-sdk-angular-cli/node_modules/loopback-sdk-angular/node_modules/ejs/lib/ejs.js:293:13)
    at Object.generateServices [as services] (/Users/berseron/npm/lib/node_modules/strongloop/node_modules/loopback-sdk-angular-cli/node_modules/loopback-sdk-angular/lib/services.js:38:14)
    at Object.<anonymous> (/Users/berseron/npm/lib/node_modules/strongloop/node_modules/loopback-sdk-angular-cli/bin/lb-ng:31:24)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

For information I use which to execute the script due to generator utilisation:

    node --harmony_generators `which lb-ng ./server/server.js ./lb-service.js`

Any idea ?

**Comment by colinkho** [comment]
I am experiencing this too. Any update?

**Comment by davidcheung** [comment]
hi @hikkyu and @colinkho, I am unable to reproduce this issue, are you using the latest version of the components? Would you be able to provide a link to a test project with steps to reproduce the issue? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report. Thanks!

**Comment by davidcheung** [comment]
Looks like @npedrini is running into same issue, leaving his comment here to help troubleshoot + reproduce
>The lb-ng command fails if any exposed models contain remoteMethod definitions where at least one argument definition is an array. This seems to counter the Loopback docs which state that arrays are supported for long strings:

**Comment by saystone** [comment]
I have same issue. any updates?

**Comment by davidcheung** [comment]
@saystone I am not able to reproduce this issue, would you be able to provide steps to reproduce

as @npedrini suggested it might be `array` arguments, but I cant get the same error
I have a function as such and it seems to work fine
```js
Peasant.remoteMethod(
  'throwError',
  { 
    http: {
      path: '/ngdoc-test',
      verb: 'get'
    },
    accepts : [
      {
        arg: 'name',
        type: 'string', 
        description: [
          'Line 1 argument desc',
          'Line 2 argument desc',
          'Line 3 argument \n Line 4 argument'
        ]
      },
      {
        arg: 'lastname',
        type: 'string', 
        description: [
          'Line 1 argument desc',
          'Line 2 argument desc',
          'Line 3 argument \n Line 4 argument'
        ]
      }
    ]
  }
);
```
```js
/**
             * @ngdoc method
             * @name lbServices.Peasant#throwError
             * @methodOf lbServices.Peasant
             *
             * @description
             *
             * <em>
             * (The remote method definition does not provide any description.)
             * </em>
             *
             * @param {Object=} parameters Request parameters.
             *
             *  - `name` – `{string=}` - Line 1 argument desc,Line 2 argument desc,Line 3 argument 
             *    Line 4 argument
             *
             *  - `lastname` – `{string=}` - Line 1 argument desc,Line 2 argument desc,Line 3 argument 
             *    Line 4 argument
             *
             * @param {function(Object,Object)=} successCb
             *   Success callback with two arguments: `value`, `responseHeaders`.
             *
             * @param {function(Object)=} errorCb Error callback with one argument:
             *   `httpResponse`.
             *
             * @returns {Object} An empty reference that will be
             *   populated with the actual data once the response is returned
             *   from the server.
             *
             * This method returns no data.
             */
            "throwError": {
              url: urlBase + "/peasants/ngdoc-test",
              method: "GET",
            },
```

**Comment by davidcheung** [comment]
@colinkho @hikkyu are u guys still experience this issue? would you guys be able to provide a sandbox to reproduce this issue? Thanks!

**Comment by git2g** [comment]
+1 - Still getting this error @davidcheung 
```
throw err;
  ^

TypeError: ejs:462
    460| function ngdocForMethod(modelName, methodName, action, responseModelName) {

```

**Comment by davidcheung** [comment]
@git2g would you be able to provide a sandbox reproducing the problem, or point out what breaks the template, I've tried to reproduce without success.

**Comment by git2g** [comment]
@davidcheung - sent an email to your IBM account with the repo information

**Comment by git2g** [comment]
@davidcheung - I also refactored the remote methods to change the args with array type to object, but still getting the same error as above when running lb-ng

**Comment by git2g** [comment]
Thanks @davidcheung - As a workaround, I refactored the **args' descriptions** for remote methods **from arrays to strings** and was able to run lb-ng successfully.
