### ISSUE TITLE
logout() doean't work

### ISSUE THREAD

**Issue by adanielyan** [strongloop/loopback-sdk-angular#165]
I have a SystemUser model that is inherited from User. The dataSource is mongodb

When I try to logout in my API explorer I get this error:
```
{
  "error": {
    "name": "Error",
    "status": 500,
    "message": "Model::findById requires the id argument",
    "stack": "Error: Model::findById requires the id argument\n    at /var/www/jjform/node_modules/loopback-datasource-juggler/lib/dao.js:741:10\n    at /var/www/jjform/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31\n    at /var/www/jjform/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31\n    at process._tickDomainCallback (node.js:486:13)\n    at process.<anonymous> (/var/www/jjform/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:18:15)"
  }
}
```

Can't figure out what I am doing wrong.

**Comment by adanielyan** [comment]
Moved it to loopback issue queue.

https://github.com/strongloop/loopback/issues/1531
