### ISSUE TITLE
Cannot resolve path "cors"

### ISSUE THREAD

**Issue by kennethlynne** [strongloop/loopback-sdk-angular#216]
All of a sudden this error message started to occur. Builds where passing on our CI up until recently, and now even rebuilding old build fails, so I am quite certain it is some of our loopback dependencies that is the culprit. 

```bash
Loading LoopBack app "/home/ubuntu/edtech-web/api/server/server.js"

/home/ubuntu/edtech-web/api/node_modules/loopback-boot/lib/compiler.js:358
    throw err;
          ^
Error: Cannot resolve path "cors"
    at resolveAppPath (/home/ubuntu/edtech-web/api/node_modules/loopback-boot/lib/compiler.js:356:15)
    at resolveAppScriptPath (/home/ubuntu/edtech-web/api/node_modules/loopback-boot/lib/compiler.js:681:22)
    at resolveMiddlewarePath (/home/ubuntu/edtech-web/api/node_modules/loopback-boot/lib/compiler.js:557:20)
    at /home/ubuntu/edtech-web/api/node_modules/loopback-boot/lib/compiler.js:475:24
    at Array.forEach (native)
    at /home/ubuntu/edtech-web/api/node_modules/loopback-boot/lib/compiler.js:474:18
    at Array.forEach (native)
    at /home/ubuntu/edtech-web/api/node_modules/loopback-boot/lib/compiler.js:469:30
    at Array.forEach (native)
    at buildMiddlewareInstructions (/home/ubuntu/edtech-web/api/node_modules/loopback-boot/lib/compiler.js:467:15)
```

**Comment by GonzaGonza** [comment]
`npm install cors`

fixed this issue

**Comment by davidcheung** [comment]
Looks like its same issue as https://github.com/strongloop/loopback-boot/issues/179, assuming they are both resolved, closing issue (feel free to reopen if its still an issue), thanks!
