### ISSUE TITLE
lb-ng

### ISSUE THREAD

**Issue by carlosalvarez91** [strongloop/loopback-sdk-angular#256]
When I try to generate lb-services at the client with lb-ng command I'm getting this error:

`bash-3.2$ lb-ng server/server.js client/www/lib/lb-services.js
Loading LoopBack app "/Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/server/server.js"

assert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: Invalid relation type: undefined
    at /Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/node_modules/loopback-datasource-juggler/lib/dataso
urce.js:458:7
    at Array.forEach (native)
    at DataSource.defineRelations (/Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/node_modules/loopback-d
atasource-juggler/lib/datasource.js:456:28)
    at DataSource.setupDataAccess (/Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/node_modules/loopback-d
atasource-juggler/lib/datasource.js:536:8)
    at DataSource.attach (/Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/node_modules/loopback-datasource
-juggler/lib/datasource.js:753:8)
    at Function.ModelClass.attachTo (/Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/node_modules/loopback
-datasource-juggler/lib/model-builder.js:339:16)
    at Registry.configureModel (/Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/node_modules/loopback/lib/
registry.js:244:15)
    at configureModel (/Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/node_modules/loopback/lib/applicati
on.js:466:16)
    at EventEmitter.app.model (/Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/node_modules/loopback/lib/a
pplication.js:140:5)
    at /Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/node_modules/loopback-boot/lib/executor.js:202:9
    at Array.forEach (native)
    at setupModels (/Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/node_modules/loopback-boot/lib/executo
r.js:198:23)
    at execute (/Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/node_modules/loopback-boot/lib/executor.js
:39:3)
    at bootLoopBackApp (/Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/node_modules/loopback-boot/index.j
s:154:3)
    at Object.<anonymous> (/Users/carlosalvarez/Desktop/APIrest/Loopback/sample copy/server/server.js:16:1)
    at Module._compile (module.js:570:32)
`
Any solution?
Thanks

**Comment by carlosalvarez91** [comment]
Issue solved:
If you are creating or modifying models manually you have to modify as well the server/model-config.json file
...a beginner mistake.

`Carloss-MBP:sample.2.0 carlosalvarez$ lb-ng server/server.js client/www/lib/lb-service.js
Loading LoopBack app "/Users/carlosalvarez/Desktop/APIrest/Loopback/sample.2.0/server/server.js"
loopback deprecated loopback.compress is deprecated. Use `require('compression');` instead. server/server.js:10:17
strong-remoting deprecated The built-in CORS middleware provided by REST adapter was deprecated. See https://docs.strongloop.com/display/public/LB/Security+considerations for more details. node_modules/strong-remoting/lib/remote-objects.js:97:25
Generating "lbServices" for the API endpoint "/api"
Warning: scope User.accessTokens targets class "AccessToken", which is not exposed 
via remoting. The Angular code for this scope won't be generated.
Warning: scope user.accessTokens targets class "AccessToken", which is not exposed 
via remoting. The Angular code for this scope won't be generated.
strong-remoting deprecated getFullPath() is deprecated, use getEndpoints()[0].fullPath instead. eval at <anonymous> (/usr/local/lib/node_modules/loopback-angular-cli/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:37:287
strong-remoting deprecated getHttpMethod() is deprecated, use getEndpoints()[0].verb instead. eval at <anonymous> (/usr/local/lib/node_modules/loopback-angular-cli/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:75:12
strong-remoting deprecated getHttpMethod() is deprecated, use getEndpoints()[0].verb instead. eval at <anonymous> (/usr/local/lib/node_modules/loopback-angular-cli/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:75:48
strong-remoting deprecated getFullPath() is deprecated, use getEndpoints()[0].fullPath instead. eval at <anonymous> (/usr/local/lib/node_modules/loopback-angular-cli/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:41:283
strong-remoting deprecated getHttpMethod() is deprecated, use getEndpoints()[0].verb instead. eval at <anonymous> (/usr/local/lib/node_modules/loopback-angular-cli/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:41:366
Saving the generated services source to "/Users/carlosalvarez/Desktop/APIrest/Loopback/sample.2.0/client/www/lib/lb-service.js"`
