### ISSUE TITLE
Unexpected behaviour with upsert if model contains related data?

### ISSUE THREAD

**Issue by louisl** [strongloop/loopback-sdk-angular#262]
If I just send the actual model data all works well but if the model data you're trying to upsert contains related data the id's for the actual model don't change.

See UPDATE values in logs below.

BarType.upsert(barType)...

With related data in the model.
```
 strong-remoting:shared-method - upsert - invoke with +0ms [
{
    id: 7,
    name: 'Belhaven',
    barAccountTypeId: 1,
    barAccountType: { id: 2, accountType: 'Independent' } /* related data */
},
  [Function: callback] ]
  loopback:connector:mysql SQL: INSERT INTO `bar_type`(`id`,`name`,`bar_account_type_id`) VALUES(?,?,?) ON DUPLICATE KEY UPDATE `name`=?,`bar_account_type_id`=?, params: [7,"Belhaven",2,"Belhaven",2] +1ms
```

Without related data in the model.
```
strong-remoting:shared-method - upsert - invoke with +0ms [ 
{
    id: 7,
    name: 'Belhaven',
    barAccountTypeId: 1
},
  [Function: callback] ]
  loopback:connector:mysql SQL: INSERT INTO `bar_type`(`id`,`name`,`bar_account_type_id`) VALUES(?,?,?) ON DUPLICATE KEY UPDATE `name`=?,`bar_account_type_id`=?, params: [7,"Belhaven",1,"Belhaven",1] +0ms
```

**Comment by louisl** [comment]
I think #252 is describing the same issue.

**Comment by bajtos** [comment]
I think this is related to how loopback-datasource-juggler handles data from relations when making updates. @kjdelisle can somebody from your team take a look please? I am pretty sure none of the AngularJS SDK code is needed to reproduce the issue, just make `GET` and `POST` requests in the same way as the SDK does it.

**Comment by xinbenlv** [comment]
Any updates?

**Comment by jannyHou** [comment]
hi @louisl, by

> the id's for the actual model don't change.

do you mean the `id` of the related model instance?

**Comment by louisl** [comment]
@jannyHou The `barAccountTypeId` for the model does change, I can confirm this by doing `{ barType | json }` in the Angular page, when passed to upsert it seems to use the related `barAccountType.id` instead of the models `barAccountTypeId` which was actually being changed to 2.

My fix for this was to to nullify the related data prior to upsert then it works as expected.
```js
function saveBarType (barType) {
  barType.barAccountType = null
  BarType.upsert(barType)
 .$promise
 .then(function (result) {
    // load new result with new relation
 })
}
```

**Comment by sebfindling** [comment]
HI, I need this too and can't figure out how. I have a Content model which has one Account via the "account" foreign key. If I do an upsert changing the account to a different Id it will throw an weird error:
```

Error no gestionado para la solicitud PATCH /Contents/5b64afe8d3780b05ac8ea99a?access_token=AqSVpR40hJnZipPTqHPDM6k6KVkr5D3rEcVWenCyUrYXnfu6zLsVjIuqH5hwPg0b: Mongo
Error: '$set' is empty. You must specify a field like so: {$set: {<field>: ...}}
    at C:\Users\Seb\dev\back\node_modules\mongodb-core\lib\connection\pool.js:595:61
    at authenticateStragglers (C:\Users\Seb\dev\back\node_modules\mongodb-core\lib\connection\pool.js:513:16)
    at Connection.messageHandler (C:\Users\Seb\dev\back\node_modules\mongodb-core\lib\connection\pool.js:549:5)
    at emitMessageHandler (C:\Users\Seb\dev\back\node_modules\mongodb-core\lib\connection\connection.js:309:10)
    at Socket.<anonymous> (C:\Users\Seb\dev\back\node_modules\mongodb-core\lib\connection\connection.js:452:17)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:635:20)
api: Contents, arg: 5b64afe8d3780b05ac8ea99a, arg2: undefined, method: PATCH, domain: localhost, token: AqSVpR40hJnZipPTqHPDM6k6KVkr5D3rEcVWenCyUrYXnfu6zLsVjIuqH5hwPg0b, quer
y { access_token:
   'AqSVpR40hJnZipPTqHPDM6k6KVkr5D3rEcVWenCyUrYXnfu6zLsVjIuqH5hwPg0b' } /Contents/5b64afe8d3780b05ac8ea99a?access_token=AqSVpR40hJnZipPTqHPDM6k6KVkr5D3rEcVWenCyUrYXnfu6zLsVjI
uqH5hwPg0b
Error no gestionado para la solicitud PATCH /Contents/5b64afe8d3780b05ac8ea99a?access_token=AqSVpR40hJnZipPTqHPDM6k6KVkr5D3rEcVWenCyUrYXnfu6zLsVjIuqH5hwPg0b: MongoError: '$se
t' is empty. You must specify a field like so: {$set: {<field>: ...}}
    at C:\Users\Seb\dev\back\node_modules\mongodb-core\lib\connection\pool.js:595:61
    at authenticateStragglers (C:\Users\Seb\dev\back\node_modules\mongodb-core\lib\connection\pool.js:513:16)
    at Connection.messageHandler (C:\Users\Seb\dev\back\node_modules\mongodb-core\lib\connection\pool.js:549:5)
    at emitMessageHandler (C:\Users\Seb\dev\back\node_modules\mongodb-core\lib\connection\connection.js:309:10)
    at Socket.<anonymous> (C:\Users\Seb\dev\back\node_modules\mongodb-core\lib\connection\connection.js:452:17)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:635:20)
api: Contents, arg: 5b64afe8d3780b05ac8ea99a, arg2: undefined, method: PATCH, domain: localhost, token: AqSVpR40hJnZipPTqHPDM6k6KVkr5D3rEcVWenCyUrYXnfu6zLsVjIuqH5hwPg0b, quer
y { access_token:
   'AqSVpR40hJnZipPTqHPDM6k6KVkr5D3rEcVWenCyUrYXnfu6zLsVjIuqH5hwPg0b' } /Contents/5b64afe8d3780b05ac8ea99a?access_token=AqSVpR40hJnZipPTqHPDM6k6KVkr5D3rEcVWenCyUrYXnfu6zLsVjI
uqH5hwPg0b
Error no gestionado para la solicitud PATCH /Contents/5b64afe8d3780b05ac8ea99a?access_token=AqSVpR40hJnZipPTqHPDM6k6KVkr5D3rEcVWenCyUrYXnfu6zLsVjIuqH5hwPg0b: MongoError: '$se
t' is empty. You must specify a field like so: {$set: {<field>: ...}}
    at C:\Users\Seb\dev\back\node_modules\mongodb-core\lib\connection\pool.js:595:61
    at authenticateStragglers (C:\Users\Seb\dev\back\node_modules\mongodb-core\lib\connection\pool.js:513:16)
    at Connection.messageHandler (C:\Users\Seb\dev\back\node_modules\mongodb-core\lib\connection\pool.js:549:5)
    at emitMessageHandler (C:\Users\Seb\dev\back\node_modules\mongodb-core\lib\connection\connection.js:309:10)
    at Socket.<anonymous> (C:\Users\Seb\dev\back\node_modules\mongodb-core\lib\connection\connection.js:452:17)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:635:20)
api: Contents, arg: 5b64afe8d3780b05ac8ea99a, arg2: undefined, method: PATCH, domain: localhost, token: AqSVpR40hJnZipPTqHPDM6k6KVkr5D3rEcVWenCyUrYXnfu6zLsVjIuqH5hwPg0b, quer
y { access_token:
   'AqSVpR40hJnZipPTqHPDM6k6KVkr5D3rEcVWenCyUrYXnfu6zLsVjIuqH5hwPg0b' } /Contents/5b64afe8d3780b05ac8ea99a?access_token=AqSVpR40hJnZipPTqHPDM6k6KVkr5D3rEcVWenCyUrYXnfu6zLsVjI
uqH5hwPg0b
Error no gestionado para la solicitud PATCH /Contents/5b64afe8d3780b05ac8ea99a?access_token=AqSVpR40hJnZipPTqHPDM6k6KVkr5D3rEcVWenCyUrYXnfu6zLsVjIuqH5hwPg0b: MongoError: '$se
t' is empty. You must specify a field like so: {$set: {<field>: ...}}
    at C:\Users\Seb\dev\back\node_modules\mongodb-core\lib\connection\pool.js:595:61
    at authenticateStragglers (C:\Users\Seb\dev\back\node_modules\mongodb-core\lib\connection\pool.js:513:16)
    at Connection.messageHandler (C:\Users\Seb\dev\back\node_modules\mongodb-core\lib\connection\pool.js:549:5)
    at emitMessageHandler (C:\Users\Seb\dev\back\node_modules\mongodb-core\lib\connection\connection.js:309:10)
    at Socket.<anonymous> (C:\Users\Seb\dev\back\node_modules\mongodb-core\lib\connection\connection.js:452:17)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:635:20)
api: Contents, arg: 5b64afe8d3780b05ac8ea99a, arg2: undefined, method: PATCH, domain: localhost, token: AqSVpR40hJnZipPTqHPDM6k6KVkr5D3rEcVWenCyUrYXnfu6zLsVjIuqH5hwPg0b, quer
y { access_token:
   'AqSVpR40hJnZipPTqHPDM6k6KVkr5D3rEcVWenCyUrYXnfu6zLsVjIuqH5hwPg0b' } /Contents/5b64afe8d3780b05ac8ea99a?access_token=AqSVpR40hJnZipPTqHPDM6k6KVkr5D3rEcVWenCyUrYXnfu6zLsVjI
uqH5hwPg0b
Error no gestionado para la solicitud PATCH /Contents/5b64afe8d3780b05ac8ea99a?access_token=AqSVpR40hJnZipPTqHPDM6k6KVkr5D3rEcVWenCyUrYXnfu6zLsVjIuqH5hwPg0b: MongoError: '$se
t' is empty. You must specify a field like so: {$set: {<field>: ...}}
    at C:\Users\Seb\dev\back\node_modules\mongodb-core\lib\connection\pool.js:595:61
    at authenticateStragglers (C:\Users\Seb\dev\back\node_modules\mongodb-core\lib\connection\pool.js:513:16)
    at Connection.messageHandler (C:\Users\Seb\dev\back\node_modules\mongodb-core\lib\connection\pool.js:549:5)
    at emitMessageHandler (C:\Users\Seb\dev\back\node_modules\mongodb-core\lib\connection\connection.js:309:10)
    at Socket.<anonymous> (C:\Users\Seb\dev\back\node_modules\mongodb-core\lib\connection\connection.js:452:17)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:635:20)


```
