### ISSUE TITLE
calling $save() to persist changes to an existing instance gets error: 'id' can't be set

### ISSUE THREAD

**Issue by fouadchamoun** [strongloop/loopback-sdk-angular#267]
### Bug or feature request
- [x] Bug
- [ ] Feature request

### Steps to reproduce
1. Get an instance from DB via findById or findOne for example.
2. Modify some properties
3. Call $save() on instance

### Link to sample repo to reproduce issue (if bug)
[Forked Sandbox](https://github.com/fouadchamoun/loopback-sandbox)
The sandbox contains demo angular code that reproduces the problem.

### Expected result
$save() should detect that instance already exists in DB and ignore the fact the 'id' is already present in object and then correctly store updated instance in DB.

### Actual result (if bug)
following the data-source-juggler source code in DAO.js (maybe this issue should be in other repo), I noticed that the server [detects](https://github.com/strongloop/loopback-datasource-juggler/blob/3.x-latest/lib/dao.js#L480) the 'id' property but continues to [create a new model instance](https://github.com/strongloop/loopback-datasource-juggler/blob/3.x-latest/lib/dao.js#L512). Calling isNewRecord on this instance returns true and thus later on when performing validations, validateAbsenceOf('id') throws the error.

### Error stack trace
```
Unhandled error for request PATCH /MyModels?id=58c7ee6cfb9ff84125e45fd0: ValidationError: The `MyModel` instance is not valid. Details: `id` can't be set (value: 58c7ee6cfb9ff84125e45fd0).
    at /home/fouad/Documents/loopback-sandbox/node_modules/loopback-datasource-juggler/lib/dao.js:540:27
    at ModelConstructor.<anonymous> (/home/fouad/Documents/loopback-sandbox/node_modules/loopback-datasource-juggler/lib/validations.js:502:11)
    at ModelConstructor.next (/home/fouad/Documents/loopback-sandbox/node_modules/loopback-datasource-juggler/lib/hooks.js:83:12)
    at ModelConstructor.<anonymous> (/home/fouad/Documents/loopback-sandbox/node_modules/loopback-datasource-juggler/lib/validations.js:499:23)
    at ModelConstructor.trigger (/home/fouad/Documents/loopback-sandbox/node_modules/loopback-datasource-juggler/lib/hooks.js:73:12)
    at ModelConstructor.Validatable.isValid (/home/fouad/Documents/loopback-sandbox/node_modules/loopback-datasource-juggler/lib/validations.js:465:8)
    at /home/fouad/Documents/loopback-sandbox/node_modules/loopback-datasource-juggler/lib/dao.js:537:16
    at doNotify (/home/fouad/Documents/loopback-sandbox/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at doNotify (/home/fouad/Documents/loopback-sandbox/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at doNotify (/home/fouad/Documents/loopback-sandbox/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at doNotify (/home/fouad/Documents/loopback-sandbox/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at Function.ObserverMixin._notifyBaseObservers (/home/fouad/Documents/loopback-sandbox/node_modules/loopback-datasource-juggler/lib/observer.js:122:5)
    at Function.ObserverMixin.notifyObserversOf (/home/fouad/Documents/loopback-sandbox/node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
    at Function.ObserverMixin._notifyBaseObservers (/home/fouad/Documents/loopback-sandbox/node_modules/loopback-datasource-juggler/lib/observer.js:120:15)
    at Function.ObserverMixin.notifyObserversOf (/home/fouad/Documents/loopback-sandbox/node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
    at Function.ObserverMixin._notifyBaseObservers (/home/fouad/Documents/loopback-sandbox/node_modules/loopback-datasource-juggler/lib/observer.js:120:15)
```

### Additional information (Node.js version, LoopBack version, etc)
Node v.6.2.2
Loopback v.3.4.0
Angular v.1.5.6

**Comment by danielskapunk** [comment]
I have the same problem, did you find a solution?

**Comment by fouadchamoun** [comment]
no nothing yet :/

**Comment by fouadchamoun** [comment]
@andela-oolutola thank you I will try this as a temporary workaround. Just gotta remember to re-modify the file if I ever regenerate it in the future.

**Comment by bajtos** [comment]
I believe this has been fixed by https://github.com/strongloop/loopback-datasource-juggler/pull/1304 in `loopback-datasource-juggler@3.6.0`. Please reopen the issue if the problem persists.
